---
title: "Zensus 2011 Variablen"
author: "Sarah Thiesen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## 1km Gitterzellen

```{r, message = FALSE, echo = FALSE}
library(dplyr)
library(purrr)
library(kableExtra)
options(knitr.kable.NA = '')

datensatzbeschr <- c("spitze", "klassierte") %>%
  map(~read.csv2(file.path("data", sprintf("Datensatzbeschreibung_%s_Werte_1km-Gitter.csv", .x)))) %>%
  map2(c("", "_cat"), ~mutate(.x, Variable = paste0(Variable, .y))) %>%
  map(~group_by(.x, Variable) %>% summarise(Label = unique(Bedeutung))) %>%
  bind_rows() %>%
  select(Label, Variable)

kableExtra::kbl(datensatzbeschr, col.names = c("Beschreibung", "Variablenname")) %>%
  kableExtra::kable_styling(full_width = TRUE) %>%
  kableExtra::pack_rows(index = c("Spitze Werte" = 10, "Klassierte Werte" = 10),
            label_row_css = "background-color: #888; color: #fff;")
```

## 100m Gitterzellen

```{r, message = FALSE, echo=FALSE}
categories <- c("Demographie", "Familien", "Haushalte", "Gebäude", "Wohnungen")
datensatzbeschr <- c("Demographie", "Familien", "Haushalt", "GebWhg", "GebWhg") %>%
  purrr::map(~read.csv2(file.path("data", sprintf("Datensatzbeschreibung_%s_100m_Gitter.csv", .x)))) %>%
  purrr::map2(categories, ~dplyr::mutate(.x, 
                                         category = .y,
                                         prefix = substring(.y, 1, 3) %>% toupper())) %>%
  dplyr::bind_rows() %>%
  tibble::as_tibble()

datensatzbeschr$Erläuterungen[datensatzbeschr$Text == "Einheiten insgesamt"] <- "Gesamtzahl der Einheiten"
  
datensatzbeschr <- dplyr::mutate(datensatzbeschr, Variable = paste(trimws(prefix), trimws(Merkmal), Code, sep = "_"),
                          Text = trimws(Text)) %>%
  dplyr::rename(Kategorie = Erläuterungen, Auspraegung = Text, Datensatz = category) %>%
  dplyr::select(Datensatz, Kategorie, Auspraegung, Variable)


filenames <- list.files(path = "/home/sarah/Daten/R/z11data/100m")
filenames <- gsub("\\.rds$", "", filenames)
df <- dplyr::right_join(datensatzbeschr, tibble::tibble(Variable = filenames))

df$Datensatz[is.na(df$Datensatz)] <- "Bevölkerung"
df$Kategorie[is.na(df$Kategorie)] <- "Einwohnerzahl"

df <- dplyr::arrange(df, Datensatz)
kat <- unique(df$Datensatz) %>% sapply(function(x) sum(df$Datensatz == x))

kableExtra::kbl(df[2:4], format = "html", col.names = c("Beschreibung", "Ausprägung", "Variablenname")) %>%
  kableExtra::pack_rows(index = kat, label_row_css = "background-color: #888; color: #fff;") %>%
  kableExtra::collapse_rows(columns = 1, valign = "top")
```
